name = "2fa-app"
main = "functions/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "2fa-app"

[[d1_databases]]
binding = "DB"
database_name = "2fa-database"
database_id = "0b02fb37-2f2e-4901-ade5-eb1c0b40c6e9"

[[kv_namespaces]]
binding = "KV"
id = "f890015bac4e4207bc480bbfa1d05ea5"
preview_id = "f890015bac4e4207bc480bbfa1d05ea5"

[build]
command = "echo 'No build needed'"
