name = "2fa-app"
main = "functions/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "2fa-app"

[[d1_databases]]
binding = "DB"
database_name = "2fa-database"
database_id = "3b257476-683c-48ed-a31f-a4fc2aa9c7a0"

[[kv_namespaces]]
binding = "KV"
id = "8131c26c757441c18aa59a0f128b800f"
preview_id = "8131c26c757441c18aa59a0f128b800f"

[build]
command = "echo 'No build needed'"
